replicaCount: 1

multitoolImage:
  repository: wbitt/network-multitool
  tag: "latest"
  pullPolicy: IfNotPresent

multitoolSpec:
  httpPort: 8080
  httpsPort: 11443

service:
  name: multitool-service
  type: ClusterIP
  httpPort: 9002
  httpsPort: 9443
