apiVersion: v1
kind: Service
metadata:
  name: netology-frontend-service
  namespace: netology
  labels:
    app: netology-nginx
spec:
  ports:
    - port: 9001
      targetPort: 80
      protocol: TCP
      name: nginx-http
  type: ClusterIP
  selector:
    app: netology-nginx
