apiVersion: v1
kind: Pod
metadata:
  name: netology-multitool
  labels:
    name: netology-multitool
spec:
  containers:
  - name: netology-multitool
    image: wbitt/network-multitool
    resources:
      limits:
        cpu: "0.1"
        memory: "128Mi"
    env:
    - name: HTTP_PORT
      value: "8080"
    - name: HTTPS_PORT
      value: "11443"
    ports:
    - containerPort: 8080
      name: http-port
    - containerPort: 11443
      name: https-port
