apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-deployment
  namespace: netology
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netology-apps
  template:
    metadata:
      labels:
        app: netology-apps
    spec:
      containers:
      - name: nginx
        imagePullPolicy: IfNotPresent
        image: nginx:1.25.1-alpine3.17
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        resources:
          limits:
            cpu: "0.1"
            memory: "128Mi"
      - name: network-multitool
        imagePullPolicy: IfNotPresent
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 11443
          name: https-port
        resources:
          limits:
            cpu: "0.1"
            memory: "128Mi"
