apiVersion: v1
kind: Service
metadata:
  name: netology-service-nodeport
  namespace: netology
spec:
  ports:
    - port: 9001
      targetPort: 80
      protocol: TCP
      name: nginx-http
    - port: 9002
      targetPort: 8080
      protocol: TCP
      name: multitool-http
    - port: 9443
      targetPort: 11443
      protocol: TCP
      name: multitool-https
  type: NodePort
  selector:
    app: netology-apps
