apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  nginxConf: {{ .Values.nginxConf | toYaml | indent 1 }}
  # nginxSite: {{ .Values.nginxSite | regexReplaceAll "Version:" (.Values.nginxImage.repository) | toYaml | indent 1 }}
  nginxSite: |
    <!DOCTYPE html>
    <html>
    <body>
      <div id = "result"> </div>
      <script>
          var myDomain = window.location.hostname;
          document.getElementById("result").innerHTML = "<br>Version: {{ .Values.nginxImage.repository }}:{{ .Chart.AppVersion }}-alpine. Domain name of the server that loaded the document: "+ myDomain;
      </script>
    </body>
    </html>
