apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /{{ .Release.Name }}/mt
        pathType: Exact
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              name: multitool-http
      - path: /{{ .Release.Name }}
        pathType: Exact
        backend:
          service:
            name: {{ .Release.Name }}-nginxservice
            port:
              name: nginx-http
