server_name: "{{ ansible_default_ipv4.address }}"
document_root: /var/www/html
app_root: lighthouse
lighthouse_repo_url: "https://github.com/VKCOM/lighthouse.git"
nginx_config_file: /etc/nginx/nginx.conf
lighthouse_nginx_config_file: /etc/nginx/conf.d/lighthouse.conf
