apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: netology-web
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080
    - containerPort: 8443
    # env:
    # - name: PORT
    #   value: "8080" и "8443" порт в данном образе всегда
    resources:
      limits:
        cpu: "0.1"
        memory: "128Mi"
