apiVersion: v1
kind: Service
metadata:
  name: netology-svc
  # namespace: echoserver
spec:
  ports:
    - port: 8081
      targetPort: 8080
      name: http
      protocol: TCP
    - port: 8082
      targetPort: 8443
      name: https
      protocol: TCP
  type: ClusterIP
  selector:
    app: netology-web
