global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
  - job_name: 'uploader'
    scrape_interval: 5s
    static_configs:
      - targets: ['uploader:3000']
    metrics_path: '/metrics'

  - job_name: 'security'
    scrape_interval: 5s
    static_configs:
      - targets: ['security:3000']
    metrics_path: '/metrics'

  - job_name: 'minio'
    scrape_interval: 5s
    static_configs:
      - targets: ['api.minio.example.com']
    metrics_path: '/minio/v2/metrics/cluster'
