---
vector_version: "0.27.0"
vector_default_config_file: /etc/default/vector
vector_config_file: /etc/vector/vector.yml
clickhouse_ipaddress: "{{ hostvars['clickhouse-01'].ansible_default_ipv4.address }}"
# clickhouse_ipaddress: "192.168.171.221"
vector_config:
  sources:
    dummy_logs:
      type: demo_logs
      format: syslog
      interval: 5
    journald_src:
        type: journald
        current_boot_only: true
        since_now: false
  sinks:
    test_console:
      type: console
      inputs:
        - dummy_logs
      encoding:
        codec: json
    clickhouse_syslog:
        type: clickhouse
        inputs:
        - journald_src
        endpoint: "http://{{ clickhouse_ipaddress }}:8123"
        database: "logs"
        table: "journald"
        skip_unknown_fields: true
