apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netology-multitool-daemonset
  namespace: netology
spec:
  selector:
    matchLabels:
      name: network-multitool
  template:
    metadata:
      labels:
        name: network-multitool
    spec:
      containers:
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 11443
          name: https-port
        resources:
          limits:
            cpu: "0.1"
            memory: "128Mi"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
