---
  - name: Installing tools
    yum: >
      name={{ item }}
      state=present
      update_cache=yes
    with_items:
      - ntp
      - python
      - tcpdump
      - wget
      - openssl
      - curl
      - git

  # - name: be sure firewalld is disabled
  #   systemd: name=firewalld enabled=no

  # - name: be sure firewalld is stopped
  #   systemd: name=firewalld state=stopped
