version: "3"
services:
  centos7:
    image: centos:7
    container_name: centos7
    stdin_open: true
    tty: true
  ubuntu:
    build: ./ubuntu
    container_name: ubuntu
    stdin_open: true
    tty: true
  fedora:
    image: fedora:38
    container_name: fedora
    stdin_open: true
    tty: true
