apiVersion: v1
kind: Service
metadata:
  name: netology-service
  namespace: netology
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx-http
  type: ClusterIP
  selector:
    app: netology-apps
